import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1760533581180 implements MigrationInterface {
    name = 'AutoGeneratedMigration1760533581180'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_9c47355777d0ea7c76aa31059cd"`);
        await queryRunner.query(`ALTER TABLE "product" RENAME COLUMN "product_type_id" TO "product_brand_id"`);
        await queryRunner.query(`ALTER TABLE "product_brand" ADD "product_type_id" integer`);
        await queryRunner.query(`ALTER TABLE "product_brand" ADD CONSTRAINT "FK_2fcca39e031ec5cd8a9007206f4" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_8e25093f12c958d5b847b76fb4e" FOREIGN KEY ("product_brand_id") REFERENCES "product_brand"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_8e25093f12c958d5b847b76fb4e"`);
        await queryRunner.query(`ALTER TABLE "product_brand" DROP CONSTRAINT "FK_2fcca39e031ec5cd8a9007206f4"`);
        await queryRunner.query(`ALTER TABLE "product_brand" DROP COLUMN "product_type_id"`);
        await queryRunner.query(`ALTER TABLE "product" RENAME COLUMN "product_brand_id" TO "product_type_id"`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_9c47355777d0ea7c76aa31059cd" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
