import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1760657827377 implements MigrationInterface {
    name = 'AutoGeneratedMigration1760657827377'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" ADD "criterion" character varying NOT NULL DEFAULT 'dona'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "criterion"`);
    }

}
