import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1760562700652 implements MigrationInterface {
    name = 'AutoGeneratedMigration1760562700652'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" ADD "isAvailable" boolean NOT NULL DEFAULT true`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "isAvailable"`);
    }

}
