import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1762862629155 implements MigrationInterface {
    name = 'AutoGeneratedMigration1762862629155'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "criterion"`);
        await queryRunner.query(`CREATE TYPE "public"."product_criterion_enum" AS ENUM('kg', 'l', 'dona')`);
        await queryRunner.query(`ALTER TABLE "product" ADD "criterion" "public"."product_criterion_enum" NOT NULL DEFAULT 'dona'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "criterion"`);
        await queryRunner.query(`DROP TYPE "public"."product_criterion_enum"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "criterion" character varying NOT NULL DEFAULT 'dona'`);
    }

}
